id: A46A9A377
title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara, the
  Glorious Victor, to Avert the Final War'
type: translation
pechas:
- ICA5CF7D3
- I57FF43C3
- I59A5219A
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:42:52.890702
  last_modified_at: 2023-01-04 11:42:52.890717
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  ICA5CF7D3/D541: '7947'
  I57FF43C3/0A86: '7947'
  I59A5219A/F423: '7947'
